### PR TITLE
Add StringArray parser

### PR DESCRIPTION
**Pull request by epsilontheta**
* Cf. https://arkpy.readthedocs.io/en/latest/formats/ (ArrayProperty [StrProperty])

### CODE REVIEW

**Comment by epsilontheta** [comment]
Could be used to e.g. parse the TribeLog and tribe members:
```
var members = parser.getStringArray('MembersPlayerName', data);
var tribelog = parser.getStringArray('TribeLog', data);
```

**Comment by epsilontheta** [comment]
Here is an example to test it:
```js
#!/usr/bin/env node

var parser = require('./lib/parse.js');
var fs = require('fs');

var argv = process.argv.slice(1); // remove node from argv
if (argv.length < 2) {
	console.log("Usage: " + argv[0] + " file1 [file2...]");
	process.exit();
}

var files = argv.slice(1);
for (var i = 0; i < files.length; i++) {
	console.log("Reading " + files[i]);
	var data = fs.readFileSync(files[i]);
	var members = parser.getStringArray('MembersPlayerName', data);
	var tribelog = parser.getStringArray('TribeLog', data);

	var log = function(item){console.log(item)};
	members.forEach(log);
	tribelog.forEach(log);
}
```

```
$ ./test.js 1029779651.arktribe
Reading 1029779651.arktribe
Nimatra
Day 4, 03:46:05: <RichColor Color="0, 1, 1, 1">Nimatra was added to the Tribe!</>
Day 4, 03:55:06: <RichColor Color="1, 1, 0, 1">Nimatra was removed from the Tribe!</>
```

**Comment by timhuijgen** [comment]
I've added this to my parser recently: 
https://www.npmjs.com/package/ark-files

**Comment by knightzac19** [comment]
I'm sorry for the late response, I haven't been keeping up with these repo much as of late. I'll let this merge in, but just a heads up, I've converted a C# library, that actually parses all ark files, to Node.JS and I'm working on trying to get it to work faster, it'll replace this project entirely. I'll hopefully be pushing it up to a new repo here soon and maybe some people can hop on and help optimize it a bit because I've lost a lot of the C# optimizations that were used when I converted it over.

**Pull request merged**
